# compose para preview
services:
  web:
    build: .
    labels:
      traefik.enable: "true"
      traefik.http.routers.preview.rule: "Host(`${PREVIEW_HOST}`)"
      traefik.http.routers.preview.entrypoints: "web"
      traefik.http.services.preview.loadbalancer.server.port: "8000"
    networks:
      - traefik
    restart: unless-stopped

networks:
  traefik:
    external: true